In [1]:
#tuple
(5,7)

(5, 7)

In [2]:
#tuple
5,7

(5, 7)

In [3]:
#tuple
(5,)

(5,)

In [4]:
list_a =[1,3,5,7,9]
list_b =[3,5,6,7,9]
list_a+list_b

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]

In [8]:
import numpy as np
array_a = np.array([1,3,5,7,9])
array_b = np.array([3,5,6,7,9])
print(array_a)
print(type(array_a))
array_a+array_b

[1 3 5 7 9]
<class 'numpy.ndarray'>


array([ 4,  8, 11, 14, 18])

In [10]:
import numpy as np

l = [[1,2,3],[2,3,4]]
array = np.array(l)
array.ndim,array.shape,array.size,array.dtype

(2, (2, 3), 6, dtype('int64'))

In [ ]:
import numpy as np
np.random.randn(10,5)

In [ ]:
#50個學生,每個學生有5個分數(50-100)
scores = np.random.randint(50,101,size=(50,5))
scores


In [18]:
#第一個學生
scores[0,:]
#前五個學生
scores[:5,:]
#最後五個學生
scores[-5:,:]

array([[ 95,  92,  85,  97,  72],
       [ 99,  55,  53,  77,  54],
       [ 68,  60,  64,  65,  63],
       [ 57,  90,  61,  82,  54],
       [ 67, 100, 100,  99,  84]])

In [19]:
#全班第1科的分數
scores[:,0]

array([70, 87, 77, 75, 72, 87, 96, 50, 99, 57, 73, 57, 82, 98, 50, 82, 56,
       93, 98, 75, 61, 66, 67, 67, 87, 84, 90, 84, 60, 82, 59, 69, 96, 76,
       97, 69, 91, 94, 66, 60, 59, 67, 65, 99, 88, 95, 99, 68, 57, 67])

In [20]:
#全班第2科的分數
scores[:,1]

array([ 95,  60,  53,  68,  96,  98,  63,  98,  98,  78,  52,  66,  79,
        63,  87,  69,  74,  57,  91,  86,  73,  89,  83,  84,  71,  57,
        64,  88,  76,  64,  83,  60,  91,  80,  99,  91,  77,  66,  52,
        87,  82,  62,  87,  97,  83,  92,  55,  60,  90, 100])

In [22]:
#每位學生的總分
total =scores[:,0]+scores[:,1]+scores[:,2]+scores[:,3]+scores[:,4]
total

array([384, 348, 352, 410, 359, 398, 378, 394, 466, 367, 379, 329, 373,
       376, 334, 390, 363, 400, 406, 355, 356, 385, 421, 378, 363, 317,
       425, 420, 342, 406, 360, 353, 428, 386, 435, 328, 394, 398, 312,
       352, 335, 332, 385, 421, 416, 441, 338, 320, 344, 450])

In [24]:
#使用統計的方法
#每個學生總分
np.sum(scores,axis=1)

array([384, 348, 352, 410, 359, 398, 378, 394, 466, 367, 379, 329, 373,
       376, 334, 390, 363, 400, 406, 355, 356, 385, 421, 378, 363, 317,
       425, 420, 342, 406, 360, 353, 428, 386, 435, 328, 394, 398, 312,
       352, 335, 332, 385, 421, 416, 441, 338, 320, 344, 450])

In [25]:
#每個學生平均
np.mean(scores,axis=1)

array([76.8, 69.6, 70.4, 82. , 71.8, 79.6, 75.6, 78.8, 93.2, 73.4, 75.8,
       65.8, 74.6, 75.2, 66.8, 78. , 72.6, 80. , 81.2, 71. , 71.2, 77. ,
       84.2, 75.6, 72.6, 63.4, 85. , 84. , 68.4, 81.2, 72. , 70.6, 85.6,
       77.2, 87. , 65.6, 78.8, 79.6, 62.4, 70.4, 67. , 66.4, 77. , 84.2,
       83.2, 88.2, 67.6, 64. , 68.8, 90. ])